### ISSUE TITLE
Protein accession number are missing in RefinedProteinDB

### ISSUE THREAD

**Issue by kahnertk** [miinslin/ProteoStorm#3]
Hello,

I encountered a problem while using ProteoStorm.

When running ProteoStrom I get a refined RefinedProteinDB.fasta where all the header information, including the protein accession number, of the original fasta file is missing. The sequences in the refinedfasta are just numbered  from 0 to 4167 (see example below).
In the result file of the run (ProteoStorm_output.txt) the identified proteins are just these protein numbers from the refined fasta.

Is this supposed to be like this or did something go wrong? 
How can I map these protein numbers back to the original accession numbers to know what proteins have been identified? 

Thank you for your time.

Best Regards,
Konstantin Kahnert

RefinedPreoteinDB.fasta (I needed to add the ' because of the formatting of github):
'>Protein_0
MGKEKIILTGDRPTGRLHIGHYVGSLKRRVDLQDAGDYSKMFIFIADSQALTDNIDNPEK[...]
'>XXX_Protein_0
EQSAAFRKVQEEILEKDDFYNIKMAKKVDALTEAAAARAVECGKQLMEYVAPIDKSFEKR[...]
'>Protein_1
MTKSIKGTQTEKNLLTSFAGESQARMRYTYFASVAKKEGYEQISAIFTETADQEKEHAKR[...]
'>XXX_Protein_1
YNEKKVEFYAQPHLCAPCVEPAEKGIEIYGCNRCQWVVEGEKAFVTMNEINNMFALYR[...]
'>Protein_2
MTLKGTKTANNLMHAFAGESQARNRYTYYASIAKKEGFVQIQNIFLETANQEKEHAKRL[...]
'>XXX_Protein_2
GLFFTNVEFHAQPHDCAPCREPAELGEFIFGCNNCKWVVPTERKFTNGAELAALLKLYR[...]

**Comment by kahnertk** [comment]
Hello,

I just noticed, that the numbers in the protein column of my output file are not the protein number from the refined database. Now I am completely confused.
So my input fasta file consists of 29 557 proteins. The refined RefinedProteinDB.fasta I get from PreoteoStorm consists of 7 765 proteins.
But the numbers in the Protein column of the ProteoStorm_output.txt file go up to 78 740 ( with a total of 37 239 entries).

I'm a bit lost here. I really hope you can help me.

Best regards,
Konstantin Kahnert

**Comment by miinslin** [comment]
Hi Konstantin,

Thank you for your interest in our tool!

In the final output, the "Protein" column refers to the header information for entries (semi-tryptic peptides) in the stage two database partitions (these database partitions are deleted by default, but intermediate files/directories will remain if the parameter --deletefiles 0 is added to the command). The only information used in the "Protein" column is whether the semi-tryptic peptide is categorized as decoy ("XXX_") or target - the numbers are simply indexes in the database partition for each entry. For FDR computation, you would use the "Protein" column and the string "XXX" to indicate a decoy sequence.

For the refined database, as we were more interested in identifications after stage two of ProteoStorm, we initially just gave each protein entry an index. **However, I just altered the code so that the entry names would be written to the refined database as well.** Depending on the initial pan-microbial database, you may have redundant protein sequences with different header information. In such cases, the header information will contain the names of the entries separated by a semicolon.

To map the identified peptides (after stage two) back to entries in the input fasta file(s), we suggest using an exact matching tool such as [PeptideMatchCMD](https://research.bioinformatics.udel.edu/peptidematch/commandlinetool.jsp). Due to the nature of database searching, where proteins are subject to _in silico_ digestion, determining the protein of origin for an identified peptide from a pan-microbial database is non-trivial. The peptide may map to proteins from multiple genera/species, and/or map to multiple proteins from the same genus/species. To identify genera, as in the publication, we used the latter criteria, where peptides assigned to a genus must only map to proteins from that specific genus.

Please refer to our manuscript for details regarding methods (STAR methods section).
